name: Timesheet CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'
      - name: Install dotnet-ef tools
        run: |
          dotnet tool install --global dotnet-ef
          dotnet tool restore
          dotnet ef database update -c TimeSheetDbContext -p ./src/Infrastructure -s ./src/WebApp
        env:
            ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
      - name: Publish
        run: dotnet publish -c Release -o ./publish
        working-directory: ./src/WebApp
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
      - name: Deploy
        run: |
          sudo cp -r ./publish/* ~/timesheet_app
        working-directory: ./src/WebApp
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
