name: Timesheet CD Workflow

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'
      - name: Stop .NET Application
        run: systemctl stop timesheet.service
      - name: Install dotnet-ef tools
        run: |
          dotnet tool install --global dotnet-ef
          dotnet tool restore
          dotnet ef database update -c TimeSheetDbContext -p ./src/Infrastructure -s ./src/WebApp
        env:
            ConnectionStrings__TimeSheetDatabase: ${{ secrets.DB_CONNECTION_STRING }}
      - name: Publish
        run: dotnet publish -c Release -o ./publish
        working-directory: ./src/WebApp
        env:
          ConnectionStrings__TimeSheetDatabase: ${{ secrets.DB_CONNECTION_STRING }}
      - name: Deploy
        run: |
          sudo cp -r ./publish/* /var/www/timesheet_app
        working-directory: ./src/WebApp
        env:
          ConnectionStrings__TimeSheetDatabase: ${{ secrets.DB_CONNECTION_STRING }}
      - name: Start .NET Application
        run: systemctl start timesheet.service
