name: Timesheet CI Workflow

on:
  pull_request:
    branches: [ main, dev ]

jobs:
    test:
        runs-on: self-hosted
        steps:
        - uses: actions/checkout@v2

        - name: Restore dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build --no-restore -c Release

        - name: Test
          run: dotnet test --no-build --verbosity normal
        